spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_management
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

server:
  port: 8080
