spring:

  datasource:
    url: jdbc:mariadb://121.156.228.45:3307/test_hyunkd?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hyunkd
    password: 1004Vision!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

server:
  port: 8080
